export const KEYS = {
    negate: 'negate',
    divide: 'divide',
    multiply: 'multiply',
    subtract: 'subtract',
    add: 'add',
    sum: 'sum',
    integrate: 'integrate',
    diff: 'diff',
    sqRoot: 'sqRoot',
    sin: 'sin',
    cos: 'cos',
    tan: 'tan',
    asin: 'asin',
    acos: 'acos',
    atan: 'atan',
    naturalLog: 'naturalLog',
    logarithm: 'logarithm',
    equals: 'equals',
    greaterThan: 'greaterThan',
    lessThan: 'lessThan',
    gtEqual: 'gtEqual',
    ltEqual: 'ltEqual',
    clear: 'clear',
    delete: 'delete',
    assign: 'assign',
    exponent: 'exponent',
    secondFunc: 'secondFunc',
    mode: 'mode',
    answer: 'answer',
    sciNotation: 'sciNotation',
    pi: 'pi',
    euler: 'euler',
}

export const DISPLAY_SYMBOL = {
    [KEYS.negate]: '( − )',
    [KEYS.divide]: '∕',
    [KEYS.multiply]: '×',
    [KEYS.subtract]: '—',
    [KEYS.add]: '+',
    [KEYS.sum]: '∑',
    [KEYS.integrate]: '∫',
    [KEYS.diff]: '∂',
    [KEYS.sqRoot]: '√',
    // cubeRoot: '∛',
    [KEYS.sin]: 'sin',
    [KEYS.cos]: 'cos',
    [KEYS.tan]: 'tan',
    [KEYS.asin]: 'sin⁻¹',
    [KEYS.acos]: 'cos⁻¹',
    [KEYS.atan]: 'tan⁻¹',
    [KEYS.naturalLog]: 'ln',
    [KEYS.logarithm]: 'log',
    [KEYS.equals]: '=',
    [KEYS.greaterThan]: '>',
    [KEYS.lessThan]: '<',
    [KEYS.gtEqual]: '≥',
    [KEYS.ltEqual]: '≤',
    [KEYS.clear]: 'C',
    [KEYS.delete]: '⌫', //␡
    [KEYS.assign]: '↦',
    [KEYS.exponent]: '^',
    [KEYS.secondFunc]: '2nd',
    [KEYS.mode]: 'mode',
    [KEYS.answer]: 'ans',
    [KEYS.sciNotation]: 'EE',
    [KEYS.pi]: 'π',
    [KEYS.euler]: 'ℯ',
}

export const CONVERTED_SYMBOL = {
    [KEYS.negate]: '-',
    [KEYS.divide]: '/',
    [KEYS.multiply]: '*',
    [KEYS.subtract]: '-',
    [KEYS.add]: '+',
    [KEYS.sum]: 'sum(',
    [KEYS.integrate]: 'integrate(',
    [KEYS.diff]: 'diff(',
    [KEYS.sqRoot]: 'sqrt(',
    // cubeRoot: '∛',
    [KEYS.sin]: 'sin(',
    [KEYS.cos]: 'cos(',
    [KEYS.tan]: 'tan(',
    [KEYS.asin]: 'asin(',
    [KEYS.acos]: 'acos(',
    [KEYS.atan]: 'atan(',
    [KEYS.naturalLog]: 'log(',
    [KEYS.logarithm]: 'log10(',
    [KEYS.equals]: '=',
    [KEYS.greaterThan]: '>',
    [KEYS.lessThan]: '<',
    [KEYS.gtEqual]: '≥',
    [KEYS.ltEqual]: '≤',
    [KEYS.clear]: 'C', // action: clear entry field
    [KEYS.delete]: '␡', // action: backspace
    [KEYS.assign]: '↦', // action: store value
    [KEYS.exponent]: '^',
    [KEYS.secondFunc]: '2nd', // action: reveal 2nd functions
    [KEYS.mode]: 'mode', // action: toggle degrees/radians
    [KEYS.answer]: 'ans', // action: recall last answer
    [KEYS.sciNotation]: '*10^(',
    [KEYS.pi]: 'Math.PI',
    [KEYS.euler]: 'Math.E',
}
