export const KEYS = {
    negate: 'negate',
    divide: 'divide',
    multiply: 'multiply',
    subtract: 'subtract',
    add: 'add',
    comma: 'comma',
    point: 'point',
    sum: 'sum',
    integrate: 'integrate',
    diff: 'diff',
    limit: 'limit',
    sqRoot: 'sqRoot',
    sin: 'sin',
    cos: 'cos',
    tan: 'tan',
    asin: 'asin',
    acos: 'acos',
    atan: 'atan',
    naturalLog: 'naturalLog',
    logarithm: 'logarithm',
    lParen: 'lParen',
    rParen: 'rParen',
    lBracket: 'lBracket',
    rBracket: 'rBracket',
    equals: 'equals',
    greaterThan: 'greaterThan',
    lessThan: 'lessThan',
    gtEqual: 'gtEqual',
    ltEqual: 'ltEqual',
    clear: 'clear',
    delete: 'delete',
    assign: 'assign',
    exponent: 'exponent',
    secondFunc: 'secondFunc',
    mode: 'mode',
    answer: 'answer',
    sciNotation: 'sciNotation',
    pi: 'pi',
    euler: 'euler',
    random: 'random',
    modulo: 'modulo',
    factorial: 'factorial',
    // nCr: 'nCr',
    // nPr: 'nPr',
    median: 'median',
    mean: 'mean',
    stdDev: 'stdDev',
    variance: 'variance',
    crossProd: 'crossProd',
    dotProd: 'dotProd',
    transpose: 'transpose',
    determinant: 'determinant',
    inverse: 'inverse',
}

export const DISPLAY_SYMBOL = {
    [KEYS.negate]: '( − )',
    [KEYS.divide]: '∕',
    [KEYS.multiply]: '*',
    [KEYS.subtract]: '—',
    [KEYS.add]: '+',
    [KEYS.point]: '.',
    [KEYS.comma]: ',',
    [KEYS.sum]: '∑',
    [KEYS.integrate]: '∫',
    [KEYS.diff]: '∂',
    [KEYS.limit]: 'lim',
    [KEYS.sqRoot]: '√',
    // cubeRoot: '∛',
    [KEYS.sin]: 'sin',
    [KEYS.cos]: 'cos',
    [KEYS.tan]: 'tan',
    [KEYS.asin]: 'sin⁻¹',
    [KEYS.acos]: 'cos⁻¹',
    [KEYS.atan]: 'tan⁻¹',
    [KEYS.naturalLog]: 'ln',
    [KEYS.logarithm]: 'log',
    [KEYS.lParen]: '(',
    [KEYS.rParen]: ')',
    [KEYS.lBracket]: '[',
    [KEYS.rBracket]: ']',
    [KEYS.equals]: '=',
    [KEYS.greaterThan]: '>',
    [KEYS.lessThan]: '<',
    [KEYS.gtEqual]: '≥',
    [KEYS.ltEqual]: '≤',
    [KEYS.clear]: 'C',
    [KEYS.delete]: '⌫', //␡
    [KEYS.assign]: '↦',
    [KEYS.exponent]: '^',
    [KEYS.secondFunc]: '2nd',
    [KEYS.mode]: 'mode',
    [KEYS.answer]: 'ans',
    [KEYS.sciNotation]: 'EE',
    [KEYS.pi]: 'π',
    [KEYS.euler]: 'ℯ',
    [KEYS.random]: 'rand',
    [KEYS.modulo]: 'mod',
    [KEYS.factorial]: '!',
    // [KEYS.nCr]: 'nCr',
    // [KEYS.nPr]: 'nPr',
    [KEYS.median]: 'med',
    [KEYS.mean]: 'x̄',
    [KEYS.stdDev]: '𝜎',
    [KEYS.variance]: '𝜎²',
    [KEYS.crossProd]: '×',
    [KEYS.dotProd]: '⋅',
    [KEYS.transpose]: 'ᵀ',
    [KEYS.determinant]: 'det',
    [KEYS.inverse]: '⁻¹',
}

export const CONVERTED_SYMBOL = {
    [KEYS.negate]: '-',
    [KEYS.divide]: '/',
    [KEYS.multiply]: '*',
    [KEYS.subtract]: '-',
    [KEYS.add]: '+',
    [KEYS.point]: '.',
    [KEYS.comma]: ',',
    [KEYS.sum]: 'sum(',
    [KEYS.integrate]: 'integrate(',
    [KEYS.diff]: 'diff(',
    [KEYS.limit]: 'limit(',
    [KEYS.sqRoot]: 'sqrt(',
    // cubeRoot: '∛',
    [KEYS.sin]: 'sin(',
    [KEYS.cos]: 'cos(',
    [KEYS.tan]: 'tan(',
    [KEYS.asin]: 'asin(',
    [KEYS.acos]: 'acos(',
    [KEYS.atan]: 'atan(',
    [KEYS.naturalLog]: 'log(',
    [KEYS.logarithm]: 'log10(',
    [KEYS.lParen]: '(',
    [KEYS.rParen]: ')',
    [KEYS.lBracket]: '[',
    [KEYS.rBracket]: ']',
    [KEYS.equals]: '=',
    [KEYS.greaterThan]: '>',
    [KEYS.lessThan]: '<',
    [KEYS.gtEqual]: '≥',
    [KEYS.ltEqual]: '≤',
    // [KEYS.clear]: 'C', // action: clear entry field
    // [KEYS.delete]: '␡', // action: backspace
    // [KEYS.assign]: '↦', // action: store value
    [KEYS.exponent]: '^',
    // [KEYS.secondFunc]: '2nd', // action: reveal 2nd functions
    // [KEYS.mode]: 'mode', // action: toggle degrees/radians
    // [KEYS.answer]: 'ans', // action: recall last answer
    [KEYS.sciNotation]: '*10^(',
    [KEYS.pi]: 'Math.PI',
    [KEYS.euler]: 'Math.E',
    [KEYS.random]: 'rand(',
    [KEYS.modulo]: 'mod(',
    [KEYS.factorial]: 'fact(',
    // [KEYS.nCr]: 'nCr',
    // [KEYS.nPr]: 'nPr',
    [KEYS.median]: 'median(',
    [KEYS.mean]: 'mean(',
    [KEYS.stdDev]: 'stdev(',
    [KEYS.variance]: 'variance(',
    [KEYS.crossProd]: 'cross(',
    [KEYS.dotProd]: 'dot(',
    [KEYS.transpose]: 'transpose(',
    [KEYS.determinant]: 'determinant(',
    [KEYS.inverse]: 'invert(',
}
