export const DISPLAY_SYMBOL = {
    negate: '( − )',
    divide: '∕',
    multiply: '×',
    subtract: '—',
    add: '+',
    sum: '∑',
    integrate: '∫',
    diff: '∂',
    sqRoot: '√',
    // cubeRoot: '∛',
    sin: 'sin',
    cos: 'cos',
    tan: 'tan',
    asin: 'sin⁻¹',
    acos: 'cos⁻¹',
    atan: 'tan⁻¹',
    naturalLog: 'ln',
    logarithm: 'log',
    equals: '=',
    greaterThan: '>',
    lessThan: '<',
    gtEqual: '≥',
    ltEqual: '≤',
    clear: 'C',
    delete: '⌫', //␡
    assign: '↦',
    exponent: '^',
    secondFunc: '2nd',
    mode: 'mode',
    answer: 'ans',
    sciNotation: 'EE',
    pi: 'π',
    euler: 'ℯ',
}

export const CONVERTED_SYMBOL = {
    negate: '-',
    divide: '/',
    multiply: '*',
    subtract: '-',
    add: '+',
    sum: 'sum(',
    integrate: 'integrate(',
    diff: 'diff(',
    sqRoot: 'sqrt(',
    // cubeRoot: '∛',
    sin: 'sin(',
    cos: 'cos(',
    tan: 'tan(',
    asin: 'asin(',
    acos: 'acos(',
    atan: 'atan(',
    naturalLog: 'log(',
    logarithm: 'log10(',
    equals: '=',
    greaterThan: '>',
    lessThan: '<',
    gtEqual: '≥',
    ltEqual: '≤',
    clear: 'C', // action: clear entry field
    delete: '␡', // action: backspace
    assign: '↦', // action: store value
    exponent: '^',
    secondFunc: '2nd', // action: reveal 2nd functions
    mode: 'mode', // action: toggle degrees/radians
    answer: 'ans', // action: recall last answer
    sciNotation: '*10^(',
    pi: 'Math.PI',
    euler: 'Math.E',
}
